# This file is based on the PIPS travis configuration.


language: julia
julia:
  - 1.0.0
sudo: required
dist: trusty

env:
  matrix:
    - TEST_WITH_MA27=0 OPENMPI=0 MPICH=1
addons:
  ssh_known_hosts: xgitlab.cels.anl.gov
  
before_install:
  - openssl aes-256-cbc -K $encrypted_c140b5346394_key -iv $encrypted_c140b5346394_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git clone git@xgitlab.cels.anl.gov:schanen/PIPSThirdPartyLibs.git
  - git clone https://github.com/michel2323/PIPS
  - cp ./PIPSThirdPartyLibs/Cbc-2.9.8.tgz ./PIPS/ThirdPartyLibs/CBC 
  - cp ./PIPSThirdPartyLibs/metis-4.0.3.tar.gz ./PIPS/ThirdPartyLibs/METIS
  - cp ./PIPSThirdPartyLibs/solvers.tar.gz ./PIPS/ThirdPartyLibs/ASL
  - if [ $TEST_WITH_MA27 -eq "0" ]; then cp ./PIPSThirdPartyLibs/ma57-3.9.0.tar.gz ./PIPS/ThirdPartyLibs/MA57; fi
  - sudo apt-get update -qq
  - sudo apt-get install -y libblas-dev liblapack-dev 
  - if [ $MPICH -eq "1" ]; then sudo apt-get install -y libmpich-dev mpich; fi
    #  - wget https://julialang-s3.julialang.org/bin/linux/x64/0.4/julia-0.4.7-linux-x86_64.tar.gz
    #  - tar xzf julia-0.4.7-linux-x86_64.tar.gz ; mv julia-ae26b25d43 julia
  
install:
  - cd PIPS ; ./build_3rdparty.sh $TEST_WITH_MA27 ; cd ..
  - cd PIPS ; ./build_pips.sh ; cd ..
  - julia -e 'Pkg.clone("https://github.com/michel2323/StructJuMP.jl")'
  - julia -e 'Pkg.checkout("StructJuMP","julia0.7")'
  - julia -e 'Pkg.clone("https://github.com/michel2323/StructJuMPSolverInterface.jl")'
  - julia -e 'Pkg.checkout("StructJuMPSolverInterface","julia0.7")'
  
script:
  - export PIPS_NLP_SHARED_LIB=$PWD/PIPS/build/PIPS-NLP/libpipsnlp.so
  - export PIPS_NLP_PAR_SHARED_LIB=$PWD/PIPS/build/PIPS-NLP/libparpipsnlp.so
  - cd examples/PowerGrid ; ./test_case9.sh
